In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [4]:
# Transformando a lista my_list em
# um NumPy array, e armazenando num variavel.
my_arr = np.array(my_list)

In [6]:
my_arr

array([1, 2, 3])

In [5]:
type(my_arr)

numpy.ndarray

In [7]:
# NumPy é bem útil para trabalhar com arrays
# multidimensionais, tornando-os até mais legíveis.
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix) # Mais óbvio que é uma matriz.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-In Functions da biblioteca NumPy

In [20]:
np.arange(0,10,3) # Similar ao range(from, to-but-not-including, step) em Python

array([0, 3, 6, 9])

In [24]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.linspace(0,10,101) # linspace(start, stop, evenly spaced numbers)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [31]:
np.eye(4) # Matriz identidade, argumento define a ordem da nossa matriz

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.random.rand(2,2) # Numeros aleatórios numa distribuição uniforme

array([[0.96162973, 0.87016751],
       [0.6544505 , 0.85262646]])

In [55]:
np.random.randn(2,3) # Numeros aleatórios numa distribuição normal (Gaussiana)

array([[ 0.64565363,  1.07916524, -0.18990938],
       [-0.72865823,  0.12814858,  0.14406907]])

In [57]:
np.random.randint(0,101, (2,5)) # Inteiros aleatórios, podem ser impressos como matriz

array([[70, 34, 81,  3,  4],
       [17, 29, 62,  5, 91]])

In [58]:
np.random.seed(42) # seed() é usado para recuperar um conjunto específico de aleatórios
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [59]:
np.random.seed(101) 
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

## Alterando o Shape de um NumPy array 

In [60]:
# Reshaping a NumPy arange()
arr = np.arange(0,20)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [64]:
arr.reshape(5,5) # Atente-se ao tamanho do array

ValueError: cannot reshape array of size 20 into shape (5,5)

In [77]:
ran_arr = np.random.rand(101,101)

In [78]:
ran_arr

array([[0.14731161, 0.12934044, 0.94405605, ..., 0.83855067, 0.52554601,
        0.37093791],
       [0.42574953, 0.26509535, 0.44640762, ..., 0.46865298, 0.93812815,
        0.44399364],
       [0.63237388, 0.28581935, 0.60864697, ..., 0.5519053 , 0.69170245,
        0.0399974 ],
       ...,
       [0.61631072, 0.25958781, 0.85005334, ..., 0.85842945, 0.30607501,
        0.01988997],
       [0.25626029, 0.76898213, 0.05374768, ..., 0.27053529, 0.87161279,
        0.73459718],
       [0.79040939, 0.38354128, 0.22252245, ..., 0.34341075, 0.3895679 ,
        0.62166413]])

In [79]:
ran_arr.min() # Valor mínimo presente no array

0.0002811319493115638

In [80]:
ran_arr.max() # Valor máximo presente no array

0.9999791510297573

In [82]:
ran_arr.argmin() # Índice em o valor mínimo está

3491

In [83]:
ran_arr.argmax() # Índice em o valor máximo está

3188

In [84]:
ran_arr.dtype

dtype('float64')

In [85]:
ran_arr.shape # Checando o shape do meu array

(101, 101)